proxy-providers:
  ID:
    type: file
    path: ./proxy_provider/id.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '100'
  MIX:
    type: file
    path: ./proxy_provider/mix.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '100'
proxy-groups:
- name: FL-ID
  type: fallback
  lazy: true
  disable-udp: false
  use:
  - ID
  url: http://www.gstatic.com/generate_204
  interval: '30'
- name: FL-X
  type: fallback
  lazy: true
  disable-udp: false
  use:
  - MIX
  url: http://www.gstatic.com/generate_204
  interval: '30'
- name: GAME
  type: select
  disable-udp: false
  proxies:
  - FL-ID
  - DIRECT
- name: BLOCK
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - FL-X
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
unified-delay: true
external-controller: 0.0.0.0:9090
secret: xidz
bind-address: 0.0.0.0
external-ui: ui
tcp-concurrent: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-filter:
    - "+.*"
  listen: 127.0.0.1:5053
  proxy-server-nameserver:
  #Ubah usb0 dengan PunyaMu#
  #Example eth0,eth1,wwan,Dll#
  #Tambahkan Alamat Ip modemmu example -192.168,xx,xx Di Bawah#
    - dhcp://"eth1"
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - https://dns.google/dns-query
  fallback:
    - 8.8.4.4
    - 1.0.0.1
    - https://dns.cloudflare.com/dns-query
  fallback-filter:
    geoip: false
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
ipv6: false
profile:
  store-selected: true
rules:
- RULE-SET,Game,GAME
- RULE-SET,PortGame,GAME
- RULE-SET,Umum,FL-X
- RULE-SET,indo,FL-ID
- RULE-SET,Sosmed,FL-ID
- RULE-SET,Streaming,FL-X
- RULE-SET,Bankid,FL-ID
- RULE-SET,Tiktok,FL-X
- RULE-SET,Meta,FL-ID
- RULE-SET,Block,BLOCK
rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./rule_provider/game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./rule_provider/portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./rule_provider/umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./rule_provider/indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./rule_provider/sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./rule_provider/streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./rule_provider/bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./rule_provider/tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./rule_provider/meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./rule_provider/block.yaml  
sniffer:
  enable: true
  parse-pure-ip: true
tun:
  enable: true
  stack: mixed
#Untuk Neko Tools Bagian Bawah True#
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
    - tcp://8.8.8.8:53
    - tcp://8.8.4.4:53
# Settingan Ini Wajib Enable METACORE #
# OPENCLASH #
# OPENWRT INDONESIA #
