#!/bin/sh

# Step 1: Configure devices (br-lan, br-voucher)
uci batch <<EOF
set network.@device[0]=device
set network.@device[0].name='br-lan'
set network.@device[0].type='bridge'
add_list network.@device[0].ports='eth0'

set network.@device[1]=device
set network.@device[1].name='br-voucher'
set network.@device[1].type='bridge'
EOF

# Step 2: Configure interfaces (lan, modemmanager, wan, tethering, chilli, hotspot_voucher)
uci batch <<EOF
# LAN interface
set network.lan=interface
set network.lan.device='br-lan'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.1.1'
set network.lan.netmask='255.255.255.0'

# ModemManager interface
set network.modemmanager=interface
set network.modemmanager.proto='modemmanager'
set network.modemmanager.device='/sys/devices/pci0000:00/0000:00:15.0/usb2/2-1/2-1.1'
set network.modemmanager.apn='internet'
set network.modemmanager.auth='none'
set network.modemmanager.iptype='ipv4'
set network.modemmanager.loglevel='ERR'
set network.modemmanager.metric='10'
set network.modemmanager.force_connection='1'

# WAN interface
set network.wan=interface
set network.wan.proto='dhcp'
set network.wan.device='eth1'
set network.wan.metric='1'

# Tethering interface
set network.tethering=interface
set network.tethering.proto='dhcp'
set network.tethering.device='usb0'
set network.tethering.metric='2'

# Chilli interface
set network.chilli=interface
set network.chilli.proto='none'
set network.chilli.device='tun0'

# Hotspot Voucher interface
set network.hotspot_voucher=interface
set network.hotspot_voucher.proto='static'
set network.hotspot_voucher.ipaddr='10.10.30.1'
set network.hotspot_voucher.netmask='255.255.255.0'
set network.hotspot_voucher.device='br-voucher'
EOF

# Step 3: Configure DNS Forwarding (to 1.1.1.1 via DHCP)
uci set dhcp.@dnsmasq[0].server='1.1.1.1'

# Step 4: Configure Firewall Zones and Forwarding
uci batch <<EOF
# LAN zone
set firewall.@zone[0]=zone
set firewall.@zone[0].name='lan'
set firewall.@zone[0].input='ACCEPT'
set firewall.@zone[0].output='ACCEPT'
set firewall.@zone[0].forward='ACCEPT'
set firewall.@zone[0].network='lan hotspot_voucher'

# WAN zone
set firewall.@zone[1]=zone
set firewall.@zone[1].name='wan'
set firewall.@zone[1].input='REJECT'
set firewall.@zone[1].output='ACCEPT'
set firewall.@zone[1].forward='REJECT'
set firewall.@zone[1].masq='1'
set firewall.@zone[1].mtu_fix='1'
set firewall.@zone[1].network='wan modemmanager tethering'

# Forwarding from LAN to WAN
set firewall.@forwarding[0]=forwarding
set firewall.@forwarding[0].src='lan'
set firewall.@forwarding[0].dest='wan'

# Chilli zone
set firewall.@zone[2]=zone
set firewall.@zone[2].name='chilli'
set firewall.@zone[2].input='ACCEPT'
set firewall.@zone[2].output='ACCEPT'
set firewall.@zone[2].forward='REJECT'
list firewall.@zone[2].network='chilli'

# Forwarding from Chilli to WAN
set firewall.@forwarding[1]=forwarding
set firewall.@forwarding[1].src='chilli'
set firewall.@forwarding[1].dest='wan'
EOF

# Step 5: Setup Wireless
uci batch <<EOF
set wireless.@wifi-device[0].disabled='0'
set wireless.@wifi-iface[0].disabled='0'
set wireless.@wifi-iface[0].encryption='none'
set wireless.@wifi-device[0].country='ID'
set wireless.@wifi-iface[0].ssid='RTA-WRT_2g'
set wireless.@wifi-device[0].channel='1'
set wireless.@wifi-device[0].band='2g'
EOF
if [ $? -ne 0 ]; then
    echo "Wireless Not Found" >> /tmp/uci-defaults.log
fi

# Commit changes and restart services
uci commit network
uci commit dhcp
uci commit firewall
uci commit wireless
/etc/init.d/network restart
/etc/init.d/dnsmasq restart
/etc/init.d/firewall restart
wifi reload && wifi up

# Log success
echo "Network Setup settings successfully applied..." >> /tmp/uci-defaults.log

# Remove this script after successful execution
rm -f /etc/uci-defaults/$(basename $0)