#!/bin/sh

# ENV
exec > /root/system-setup.log 2>&1

msg() {
    local DATE=$(date '+%d %B %Y %T')
    echo "[ INFO SYSTEM ] $1"
}


# Step 1: Configure profile Dashboard
msg "Step 1: Configure profile Dashboard"
sed -i 's/\[ -f \/etc\/banner \] && cat \/etc\/banner/#&/' /etc/profile
sed -i 's/\[ -n "$FAILSAFE" \] && cat \/etc\/banner.failsafe/& || \/usr\/bin\/rtawrt/' /etc/profile
mv /www/luci-static/resources/view/status/include/29_temp.js /www/luci-static/resources/view/status/include/17_temp.js


# Step 2: Configure Password Login OpenWrt
msg "Step 2: Configure Password Login OpenWrt"
(echo "rtawrt"; sleep 1; echo "rtawrt") | passwd > /dev/null


# Step 3: Add Custom Repo and Disable opkg signature check
msg "Step 3: Add Custom Repo and Disable opkg signature check"
sed -i 's/option check_signature/# option check_signature/g' /etc/opkg.conf
echo "src/gz custom_arch https://dl.openwrt.ai/latest/packages/$(grep "OPENWRT_ARCH" /etc/os-release | awk -F '"' '{print $2}')/kiddin9" >> /etc/opkg/customfeeds.conf


# Step 4: Set Material as default theme
msg "Step 4: Set Material as default theme"
uci set luci.main.mediaurlbase='/luci-static/material'
uci commit luci


# Step 5: Set All permission files
msg "Step 5: Set All permission files"
check_permission() {
    local DIR=${1:-.}

    find "$DIR" -type f | while read file; do
        if file "$file" | grep -q "executable"; then
            if [ ! -x "$file" ]; then
                msg "File requiring chmod +x: $file"
                chmod +x "$file"
            fi
        fi
    done
}

check_permission "/etc/init.d"
check_permission "/etc/mihomo"
check_permission "/etc/openclash"
check_permission "/lib/netifd"
check_permission "/lib/wifi"
check_permission "/sbin"
check_permission "/usr/bin"


# Log success
msg "System Setup settings successfully applied..."

# Remove this script after successful execution
rm -f /etc/uci-defaults/$(basename $0)