#!/bin/sh

# ENV
exec > /root/firs-setup.log 2>&1

msg() {
    local DATE=$(date '+%d %B %Y %T')
    echo "[ INFO FIRST SETUP ] $1"
    logger -p "notice" "[ INFO FIRST SETUP ] $1"
}


# Step 1: Configure Password Login OpenWrt
msg "Step 1: Configure Password Login OpenWrt"
(echo "rtawrt"; sleep 1; echo "rtawrt") | passwd > /dev/null


# Step 2: Add Custom Repo and Disable opkg signature check
msg "Step 2: Add Custom Repo and Disable opkg signature check"
sed -i 's/option check_signature/# option check_signature/g' /etc/opkg.conf
echo "src/gz custom_arch https://dl.openwrt.ai/latest/packages/$(grep "OPENWRT_ARCH" /etc/os-release | awk -F '"' '{print $2}')/kiddin9" >> /etc/opkg/customfeeds.conf


# Step 3: Remove sysinfo banner if Devices Amlogic
msg "Step 3: Remove sysinfo banner if Devices Amlogic"
if opkg list-installed | grep -q "^luci-app-amlogic "; then
    rm -rf /etc/profile.d/30-sysinfo.sh
fi


# Step 3: Remove login password required when accessing terminal
msg "Step 3: Remove login password required when accessing terminal"
uci set ttyd.@ttyd[0].command='/bin/bash --login'
uci commit ttyd


# Step 4: Remove huawei me909s usb-modeswitch
msg "Step 4: Remove huawei me909s usb-modeswitch"
sed -i -e '/12d1:15c1/,+5d' /etc/usb-mode.json


# Step 5: Remove dw5821e usb-modeswitch
msg "Step 5: Remove dw5821e usb-modeswitch"
sed -i -e '/413c:81d7/,+5d' /etc/usb-mode.json


# Step 6: Disable /etc/config/xmm-modem
msg "Step 6: Disable /etc/config/xmm-modem"
uci set xmm-modem.@xmm-modem[0].enable='0'
uci commit xmm-modem


# Step 7: Setup Nlbwmon Database Dir
msg "Step 7: Setup Nlbwmon Database Dir"
uci set nlbwmon.@nlbwmon[0].database_directory='/etc/nlbwmon'
uci set nlbwmon.@nlbwmon[0].commit_interval='3h'
uci set nlbwmon.@nlbwmon[0].refresh_interval='60s'
uci commit nlbwmon
bash /etc/init.d/nlbwmon restart


# Step 8: Setup Auto Vnstat Database Backup
msg "Step 8: Setup Auto Vnstat Database Backup"
sed -i 's/;DatabaseDir "\/var\/lib\/vnstat"/DatabaseDir "\/etc\/vnstat"/' /etc/vnstat.conf
mkdir -p /etc/vnstat
chmod +x /etc/init.d/vnstat_backup
bash /etc/init.d/vnstat_backup enable


# Step 9: Adjusting App Catagory
msg "Step 9: Adjusting App Catagory"
sed -i -E "s|status|services|g" /usr/lib/lua/luci/controller/base64.lua


# Step 10: Configurating OpenClash
msg "Step 10: Configurating OpenClash"
bash /usr/bin/patchoc.sh
sed -i '/exit 0/i #/usr/bin/patchoc.sh' /etc/rc.local
ln -s /etc/openclash/history/config-wrt.db /etc/openclash/cache.db
ln -s /etc/openclash/core/clash_meta  /etc/openclash/clash


# Step 11: Adding New Line For Enable i2c Oled Display if Devices Supported
msg "Step 11: Adding New Line For Enable i2c Oled Display if Devices Supported"
if grep -q "Raspberry Pi 4\|Raspberry Pi 3" /proc/cpuinfo; then
    echo -e "\ndtparam=i2c1=on\ndtparam=spi=on\ndtparam=i2s=on" >> /boot/config.txt
fi


# Step 12: Setup PHP
msg "Step 12: Setup PHP"
ln -s /usr/bin/php-cli /usr/bin/php


# Step 13: Setting Tinyfm
msg "Step 13: Setting Tinyfm"
ln -s / /www/tinyfm/rootfs

# Step 14: Patch OpenClash
msg "Step 14: Patch OpenClash"
STATUS="/usr/lib/lua/luci/view/openclash/status.htm"
DEV="/usr/lib/lua/luci/view/openclash/developer.htm"
MYIP="/usr/lib/lua/luci/view/openclash/myip.htm"
IMG="/luci-static/resources/openclash/img"
CLIENT="/usr/lib/lua/luci/model/cbi/openclash/client.lua"
CONT="/usr/lib/lua/luci/controller/openclash.lua"

[ -f "/www/${IMG}/logo.png" ] && sed -i "s#https://ftp.jaist.ac.jp/pub/sourceforge.jp/storage/g/o/op/openclash/<%=RELEASE_BRANCH%>/img/logo.png#$IMG/logo.png#g" $STATUS
[ -f "/www/${IMG}/meta.png" ] && sed -i "s#https://ftp.jaist.ac.jp/pub/sourceforge.jp/storage/g/o/op/openclash/<%=RELEASE_BRANCH%>/img/meta.png#$IMG/meta.png#g" $STATUS
[ -f "/www/${IMG}/Wiki.svg" ] && sed -i "s#https://img.shields.io/badge/Wiki--lightgrey?logo=GitBook&style=social#$IMG/Wiki.svg#g" $STATUS
[ -f "/www/${IMG}/Tutorials.svg" ] && sed -i "s#https://img.shields.io/badge/Tutorials--lightgrey?logo=Wikipedia&style=social#$IMG/Tutorials.svg#g" $STATUS
[ -f "/www/${IMG}/Star.svg" ] && sed -i "s#https://img.shields.io/badge/Star--lightgrey?logo=github&style=social#$IMG/Star.svg#g" $STATUS
[ -f "/www/${IMG}/Telegram.svg" ] && sed -i "s#https://img.shields.io/badge/Telegram--lightgrey?logo=Telegram&style=social#$IMG/Telegram.svg#g" $STATUS
[ -f "/www/${IMG}/Sponsor.svg" ] && sed -i "s#https://img.shields.io/badge/Sponsor--lightgrey?logo=ko-fi&style=social#$IMG/Sponsor.svg#g" $STATUS

if ! grep -qE "\-\- s:section|\-\-s:section" $CLIENT
then
	sed -i "s#s:section#-- s:section#g" $CLIENT
	mv $MYIP $MYIP.bak
	cat << 'EOF' > $MYIP
<!DOCTYPE html>
<html>
</html>
EOF
fi

if grep -q 'githubusercontent.com' $DEV
then
	sed -i 's#translate("Credits")#translate("")#g' $CLIENT
	mv $DEV $DEV.bak
	cat << 'EOF' > $DEV
<style>
.developer_ {
  text-align: justify;
  text-align-last: justify;
}
</style>
<fieldset class="cbi-section">
    <div class="developer_">
        <table width="100%"><tr><td>
        <span id="_Dreamacro"><%:Dreamacro%></span>
        <span id="_vernesong"><%:Vernesong%></span>
        <span id="_frainzy1477"><%:Frainzy1477%></span>
        <span id="_SukkaW"><%:SukkaW%></span>
        <span id="_lhie1_dev"><%:lhie1_dev%></span>
        <span id="_ConnersHua_dev"><%:ConnersHua_dev%></span>
        <span id="_haishanh"><%:Haishanh%></span>
        <span id="_MaxMind"><%:MaxMind%></span>
        <span id="_FQrabbit"><%:FQrabbit%></span>
        <span id="_Alecthw"><%:Alecthw%></span>
        <span id="_Tindy_X"><%:Tindy_X%></span>
        <span id="_lmc999"><%:lmc999%></span>
        <span id="_dlercloud"><%:Dlercloud%></span>
        <span id="_immortalwrt"><%:Immortalwrt%></span>
        <span id="_MetaCubeX"><%:MetaCubeX%></span>
        </td></tr></table>
    </div>
</fieldset>
EOF
fi

sed -i '87 i\	entry({"admin", "services", "openclash", "editor"}, template("openclash/editor"),_("Config Editor"), 90).leaf = true' $CONT
cat << EOF > /usr/lib/lua/luci/view/openclash/editor.htm
<%+header%>
<div class="cbi-map">
<iframe id="editor" style="width: 100%; min-height: 100vh; border: none; border-radius: 2px;"></iframe>
</div>
<script type="text/javascript">
document.getElementById("editor").src = "http://" + window.location.hostname + "/tinyfm/tinyfm.php?p=etc/openclash";
</script>
<%+footer%>
EOF



# Step 16: Set All permission files
msg "Step 16: Set All permission files"
check_permission() {
    local DIR=${1:-.}

    find "$DIR" -type f | while read file; do
        if file "$file" | grep -q "executable"; then
            if [ ! -x "$file" ]; then
                msg "File requiring chmod +x: $file"
                chmod +x "$file"
            fi
        fi
    done
}

check_permission "/etc/init.d"
check_permission "/etc/mihomo"
check_permission "/etc/openclash"
check_permission "/lib/netifd"
check_permission "/lib/wifi"
check_permission "/sbin"
check_permission "/usr/bin"

# Step 17: Run Another Process
msg "Step 17: Run Another Process"
bash /root/install2.sh

# Log success
msg "First Setup settings successfully applied..."

# Remove this script after successful execution
rm -f /etc/uci-defaults/$(basename $0)

# Reboot After Steps Complited
# reboot || echo b > /proc/sysrq-trigger
